In [160]:
import pandas as pd
df = pd.read_csv("data/carPrices/train.csv")

In [161]:
df.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [162]:
df.count()

ID                  19237
Price               19237
Levy                19237
Manufacturer        19237
Model               19237
Prod. year          19237
Category            19237
Leather interior    19237
Fuel type           19237
Engine volume       19237
Mileage             19237
Cylinders           19237
Gear box type       19237
Drive wheels        19237
Doors               19237
Wheel               19237
Color               19237
Airbags             19237
dtype: int64

In [163]:
df.describe()

                 ID         Price    Prod. year     Cylinders       Airbags
count  1.923700e+04  1.923700e+04  19237.000000  19237.000000  19237.000000
mean   4.557654e+07  1.855593e+04   2010.912824      4.582991      6.582627
std    9.365914e+05  1.905813e+05      5.668673      1.199933      4.320168
min    2.074688e+07  1.000000e+00   1939.000000      1.000000      0.000000
25%    4.569837e+07  5.331000e+03   2009.000000      4.000000      4.000000
50%    4.577231e+07  1.317200e+04   2012.000000      4.000000      6.000000
75%    4.580204e+07  2.207500e+04   2015.000000      4.000000     12.000000
max    4.581665e+07  2.630750e+07   2020.000000     16.000000     16.000000

In [164]:
df.tail()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,04-May,Left wheel,White,12

In [165]:
df.nunique()

ID                  18924
Price                2315
Levy                  559
Manufacturer           65
Model                1590
Prod. year             54
Category               11
Leather interior        2
Fuel type               7
Engine volume         107
Mileage              7687
Cylinders              13
Gear box type           4
Drive wheels            3
Doors                   3
Wheel                   2
Color                  16
Airbags                17
dtype: int64

In [166]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19237 non-null  int64
 1   Price             19237 non-null  int64
 2   Levy              19237 non-null  str
 3   Manufacturer      19237 non-null  str
 4   Model             19237 non-null  str
 5   Prod. year        19237 non-null  int64
 6   Category          19237 non-null  str
 7   Leather interior  19237 non-null  str
 8   Fuel type         19237 non-null  str
 9   Engine volume     19237 non-null  str
 10  Mileage           19237 non-null  str
 11  Cylinders         19237 non-null  float64
 12  Gear box type     19237 non-null  str
 13  Drive wheels      19237 non-null  str
 14  Doors             19237 non-null  str
 15  Wheel             19237 non-null  str
 16  Color             19237 non-null  str
 17  Airbags           19237 non-null  int64
dtypes: float64(1), int64(4), str(13)
memory usage: 2.6 MB

In [167]:
df = df.drop(columns=['Levy', 'ID'])

In [168]:
df.head()

,Price,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,13328,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,16621,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,8467,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,3607,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,11726,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [169]:
df.nunique()

Price               2315
Manufacturer          65
Model               1590
Prod. year            54
Category              11
Leather interior       2
Fuel type              7
Engine volume        107
Mileage             7687
Cylinders             13
Gear box type          4
Drive wheels           3
Doors                  3
Wheel                  2
Color                 16
Airbags               17
dtype: int64

In [170]:
df['Mileage'] = df['Mileage'].str.replace('km', '', regex=False)

In [171]:
df['Mileage'] = df['Mileage'].astype(int)

In [172]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             19237 non-null  int64
 1   Manufacturer      19237 non-null  str
 2   Model             19237 non-null  str
 3   Prod. year        19237 non-null  int64
 4   Category          19237 non-null  str
 5   Leather interior  19237 non-null  str
 6   Fuel type         19237 non-null  str
 7   Engine volume     19237 non-null  str
 8   Mileage           19237 non-null  int64
 9   Cylinders         19237 non-null  float64
 10  Gear box type     19237 non-null  str
 11  Drive wheels      19237 non-null  str
 12  Doors             19237 non-null  str
 13  Wheel             19237 non-null  str
 14  Color             19237 non-null  str
 15  Airbags           19237 non-null  int64
dtypes: float64(1), int64(4), str(11)
memory usage: 2.3 MB

In [173]:
df['Wheel'] = df['Wheel'].map({'Right-hand drive': 0, 'Left wheel': 1})

In [174]:
df.tail()

,Price,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
19232,8467,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000,4.0,Manual,Rear,02-Mar,1,Silver,5
19233,15681,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600,4.0,Tiptronic,Front,04-May,1,Red,8
19234,26108,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365,4.0,Automatic,Front,04-May,1,Grey,4
19235,5331,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258,4.0,Automatic,Front,04-May,1,Black,4
19236,470,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923,4.0,Automatic,Front,04-May,1,White,12

In [175]:
df.nunique()

Price               2315
Manufacturer          65
Model               1590
Prod. year            54
Category              11
Leather interior       2
Fuel type              7
Engine volume        107
Mileage             7687
Cylinders             13
Gear box type          4
Drive wheels           3
Doors                  3
Wheel                  2
Color                 16
Airbags               17
dtype: int64

In [176]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             19237 non-null  int64
 1   Manufacturer      19237 non-null  str
 2   Model             19237 non-null  str
 3   Prod. year        19237 non-null  int64
 4   Category          19237 non-null  str
 5   Leather interior  19237 non-null  str
 6   Fuel type         19237 non-null  str
 7   Engine volume     19237 non-null  str
 8   Mileage           19237 non-null  int64
 9   Cylinders         19237 non-null  float64
 10  Gear box type     19237 non-null  str
 11  Drive wheels      19237 non-null  str
 12  Doors             19237 non-null  str
 13  Wheel             19237 non-null  int64
 14  Color             19237 non-null  str
 15  Airbags           19237 non-null  int64
dtypes: float64(1), int64(5), str(10)
memory usage: 2.3 MB

In [177]:
df['Cylinders'] = df['Cylinders'].astype(int)

In [178]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             19237 non-null  int64
 1   Manufacturer      19237 non-null  str
 2   Model             19237 non-null  str
 3   Prod. year        19237 non-null  int64
 4   Category          19237 non-null  str
 5   Leather interior  19237 non-null  str
 6   Fuel type         19237 non-null  str
 7   Engine volume     19237 non-null  str
 8   Mileage           19237 non-null  int64
 9   Cylinders         19237 non-null  int64
 10  Gear box type     19237 non-null  str
 11  Drive wheels      19237 non-null  str
 12  Doors             19237 non-null  str
 13  Wheel             19237 non-null  int64
 14  Color             19237 non-null  str
 15  Airbags           19237 non-null  int64
dtypes: int64(6), str(10)
memory usage: 2.3 MB

In [179]:
df['Category'].unique()

<StringArray>
[       'Jeep',   'Hatchback',       'Sedan',    'Microbus', 'Goods wagon',
   'Universal',       'Coupe',     'Minivan',   'Cabriolet',   'Limousine',
      'Pickup']
Length: 11, dtype: str

In [180]:
BODY_TYPE_MAP = {
    "Jeep": "SUV",
    "Hatchback": "Hatchback",
    "Sedan": "Sedan",
    "Microbus": "Van",
    "Goods wagon": "Van",
    "Universal": "Wagon",
    "Coupe": "Coupe",
    "Minivan": "Van",
    "Cabriolet": "Convertible",
    "Limousine": "Sedan",
    "Pickup": "Pickup",
}
df['Category'] = df['Category'].map(BODY_TYPE_MAP)

In [181]:
df['Gear box type'].unique()

<StringArray>
['Automatic', 'Tiptronic', 'Variator', 'Manual']
Length: 4, dtype: str

In [182]:
df['Leather interior'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [183]:
df.nunique()

Price               2315
Manufacturer          65
Model               1590
Prod. year            54
Category               8
Leather interior       2
Fuel type              7
Engine volume        107
Mileage             7687
Cylinders             13
Gear box type          4
Drive wheels           3
Doors                  3
Wheel                  2
Color                 16
Airbags               17
dtype: int64

In [184]:
GEARBOX_TYPE_MAP = {
    "Automatic": "Automatic",
    "Tiptronic": "Automatic",
    "Variator": "Automatic",  # CVT
    "Manual": "Manual",
}

In [185]:
df['Gear box type'] = df['Gear box type'].map(GEARBOX_TYPE_MAP)

In [186]:
df['Gear box type'].unique()

<StringArray>
['Automatic', 'Manual']
Length: 2, dtype: str

In [187]:
df['Gear box type'] = df['Gear box type'].map({'Manual': 1, 'Automatic': 0})

In [188]:
df['Fuel type'].unique()

<StringArray>
['Hybrid', 'Petrol', 'Diesel', 'CNG', 'Plug-in Hybrid', 'LPG', 'Hydrogen']
Length: 7, dtype: str

In [189]:
drive_wheels_map = {
    '4x4': 'AWD',
    'Front': 'FWD',
    'Rear': 'RWD'}
df['Drive wheels'] = df['Drive wheels'].map(drive_wheels_map)

In [190]:
fuel_type_map = {
    "Hybrid": "Hybrid",
    "Plug-in Hybrid": "Hybrid",
    "Petrol": "Petrol",
    "Diesel": "Diesel",
    "CNG": "Petrol",
    "LPG": "Petrol",
    "Hydrogen": "Electric",
}
df['Fuel type'] = df['Fuel type'].map(fuel_type_map)

In [191]:
df['Doors'].unique()

<StringArray>
['04-May', '02-Mar', '>5']
Length: 3, dtype: str

In [192]:
df = df.drop(columns=['Doors'])

In [193]:
df.nunique()

Price               2315
Manufacturer          65
Model               1590
Prod. year            54
Category               8
Leather interior       2
Fuel type              4
Engine volume        107
Mileage             7687
Cylinders             13
Gear box type          2
Drive wheels           3
Wheel                  2
Color                 16
Airbags               17
dtype: int64

In [194]:
df = pd.get_dummies(df, columns=['Color', 'Category', 'Fuel type', 'Drive wheels'], drop_first=False)

In [195]:
df.head()

,Price,Manufacturer,Model,Prod. year,Leather interior,Engine volume,Mileage,Cylinders,Gear box type,Wheel,...,Category_Sedan,Category_Van,Category_Wagon,Fuel type_Diesel,Fuel type_Electric,Fuel type_Hybrid,Fuel type_Petrol,Drive wheels_AWD,Drive wheels_FWD,Drive wheels_RWD
0,13328,LEXUS,RX 450,2010,Yes,3.5,186005,6,0,1,...,False,False,False,False,False,True,False,True,False,False
1,16621,CHEVROLET,Equinox,2011,No,3,192000,6,0,1,...,False,False,False,False,False,False,True,True,False,False
2,8467,HONDA,FIT,2006,No,1.3,200000,4,0,0,...,False,False,False,False,False,False,True,False,True,False
3,3607,FORD,Escape,2011,Yes,2.5,168966,4,0,1,...,False,False,False,False,False,True,False,True,False,False
4,11726,HONDA,FIT,2014,Yes,1.3,91901,4,0,1,...,False,False,False,False,False,False,True,False,True,False

In [196]:
df.isna().sum()

Price                   0
Manufacturer            0
Model                   0
Prod. year              0
Leather interior        0
Engine volume           0
Mileage                 0
Cylinders               0
Gear box type           0
Wheel                   0
Airbags                 0
Color_Beige             0
Color_Black             0
Color_Blue              0
Color_Brown             0
Color_Carnelian red     0
Color_Golden            0
Color_Green             0
Color_Grey              0
Color_Orange            0
Color_Pink              0
Color_Purple            0
Color_Red               0
Color_Silver            0
Color_Sky blue          0
Color_White             0
Color_Yellow            0
Category_Convertible    0
Category_Coupe          0
Category_Hatchback      0
Category_Pickup         0
Category_SUV            0
Category_Sedan          0
Category_Van            0
Category_Wagon          0
Fuel type_Diesel        0
Fuel type_Electric      0
Fuel type_Hybrid        0
Fuel type_Petrol        0
Drive wheels_AWD        0
Drive wheels_FWD        0
Drive wheels_RWD        0
dtype: int64

In [197]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 42 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Price                 19237 non-null  int64
 1   Manufacturer          19237 non-null  str
 2   Model                 19237 non-null  str
 3   Prod. year            19237 non-null  int64
 4   Leather interior      19237 non-null  str
 5   Engine volume         19237 non-null  str
 6   Mileage               19237 non-null  int64
 7   Cylinders             19237 non-null  int64
 8   Gear box type         19237 non-null  int64
 9   Wheel                 19237 non-null  int64
 10  Airbags               19237 non-null  int64
 11  Color_Beige           19237 non-null  bool
 12  Color_Black           19237 non-null  bool
 13  Color_Blue            19237 non-null  bool
 14  Color_Brown           19237 non-null  bool
 15  Color_Carnelian red   19237 non-null  bool
 16  Color_Golden          19237 non-null  bool
 17  Color_Green           19237 non-null  bool
 18  Color_Grey            19237 non-null  bool
 19  Color_Orange          19237 non-null  bool
 20  Color_Pink            19237 non-null  bool
 21  Color_Purple          19237 non-null  bool
 22  Color_Red             19237 non-null  bool
 23  Color_Silver          19237 non-null  bool
 24  Color_Sky blue        19237 non-null  bool
 25  Color_White           19237 non-null  bool
 26  Color_Yellow          19237 non-null  bool
 27  Category_Convertible  19237 non-null  bool
 28  Category_Coupe        19237 non-null  bool
 29  Category_Hatchback    19237 non-null  bool
 30  Category_Pickup       19237 non-null  bool
 31  Category_SUV          19237 non-null  bool
 32  Category_Sedan        19237 non-null  bool
 33  Category_Van          19237 non-null  bool
 34  Category_Wagon        19237 non-null  bool
 35  Fuel type_Diesel      19237 non-null  bool
 36  Fuel type_Electric    19237 non-null  bool
 37  Fuel type_Hybrid      19237 non-null  bool
 38  Fuel type_Petrol      19237 non-null  bool
 39  Drive wheels_AWD      19237 non-null  bool
 40  Drive wheels_FWD      19237 non-null  bool
 41  Drive wheels_RWD      19237 non-null  bool
dtypes: bool(31), int64(7), str(4)
memory usage: 2.2 MB

In [198]:
df['Leather interior'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [199]:
df['Leather interior'].map({'Yes': 1, 'No': 0})

0        1
1        0
2        0
3        1
4        1
        ..
19232    1
19233    1
19234    1
19235    1
19236    1
Name: Leather interior, Length: 19237, dtype: int64

In [200]:
df['Leather interior'] = df['Leather interior'].map({'Yes': 1, 'No': 0})

In [201]:
df.isna().sum()

Price                   0
Manufacturer            0
Model                   0
Prod. year              0
Leather interior        0
Engine volume           0
Mileage                 0
Cylinders               0
Gear box type           0
Wheel                   0
Airbags                 0
Color_Beige             0
Color_Black             0
Color_Blue              0
Color_Brown             0
Color_Carnelian red     0
Color_Golden            0
Color_Green             0
Color_Grey              0
Color_Orange            0
Color_Pink              0
Color_Purple            0
Color_Red               0
Color_Silver            0
Color_Sky blue          0
Color_White             0
Color_Yellow            0
Category_Convertible    0
Category_Coupe          0
Category_Hatchback      0
Category_Pickup         0
Category_SUV            0
Category_Sedan          0
Category_Van            0
Category_Wagon          0
Fuel type_Diesel        0
Fuel type_Electric      0
Fuel type_Hybrid        0
Fuel type_Petrol        0
Drive wheels_AWD        0
Drive wheels_FWD        0
Drive wheels_RWD        0
dtype: int64

In [202]:
df['Engine volume'] = df['Engine volume'].map(df['Engine volume'].value_counts())

In [203]:
df['Manufacturer'] = df['Manufacturer'].map(df['Manufacturer'].value_counts())

In [204]:
df.head()

,Price,Manufacturer,Model,Prod. year,Leather interior,Engine volume,Mileage,Cylinders,Gear box type,Wheel,...,Category_Sedan,Category_Van,Category_Wagon,Fuel type_Diesel,Fuel type_Electric,Fuel type_Hybrid,Fuel type_Petrol,Drive wheels_AWD,Drive wheels_FWD,Drive wheels_RWD
0,13328,982,RX 450,2010,1,1228,186005,6,0,1,...,False,False,False,False,False,True,False,True,False,False
1,16621,1069,Equinox,2011,0,823,192000,6,0,1,...,False,False,False,False,False,False,True,True,False,False
2,8467,977,FIT,2006,0,518,200000,4,0,0,...,False,False,False,False,False,False,True,False,True,False
3,3607,1111,Escape,2011,1,2277,168966,4,0,1,...,False,False,False,False,False,True,False,True,False,False
4,11726,977,FIT,2014,1,518,91901,4,0,1,...,False,False,False,False,False,False,True,False,True,False

In [205]:
model_mean = df.groupby('Model')['Price'].mean()

In [206]:
model_mean

Model
09-Mar       6920.000000
100         12819.000000
100 NX       5331.000000
1000         3620.176471
1111         4000.000000
               ...
kona        45473.000000
macan      109450.000000
macan S    103178.000000
tC          19233.666667
xD          14531.000000
Name: Price, Length: 1590, dtype: float64

In [207]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['Price'])
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [208]:
train_df = X_train.copy()
train_df['Price'] = y_train

In [209]:
model_avg = train_df.groupby('Model')['Price'].mean()

In [211]:
X_train['Model_encoded'] = X_train['Model'].map(model_avg)
X_test['Model_encoded'] = X_test['Model'].map(model_avg)

In [212]:
global_avg = train_df['Price'].mean()
X_test['Model_encoded'] = X_test['Model_encoded'].fillna(global_avg)